blank_issues_enabled: false
contact_links:
  - name: 💬 Ask a Question
    url: https://github.com/eliezedeck/AIDevTools/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🔒 Security Vulnerability
    url: https://github.com/eliezedeck/AIDevTools/security/advisories/new
    about: Report security vulnerabilities privately
  - name: 📚 Documentation
    url: https://github.com/eliezedeck/AIDevTools#readme
    about: Check the documentation for setup and usage guides